### ISSUE TITLE
is snap provided?

### ISSUE THREAD

**Issue by mukhrr** [dapi-labs/react-horizontal-scrolling#3]
Hi guys, does `react-horizontal-scrolling` support snap? I mean like this

https://user-images.githubusercontent.com/71601329/173005806-ec62423d-7fa1-461e-86f0-11c82266a4a6.mp4

**Comment by wwayne** [comment]
Not supported, but I happened to find twitter talking about such effect with pure CSS, you might be interested https://twitter.com/Steve8708/status/1531388545960583168
