### ISSUE TITLE
I can't install this package

### ISSUE THREAD

**Issue by davidmedero** [dapi-labs/react-horizontal-scrolling#4]
This is my error. I've been trying to fix it all day. I even tried this on a completely new project with only React 16 installed. I tried npm install --legacy-peer-deps, npm i --force, pretty much everything

npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ">=^16.0.0" of package "react@>=^16.0.0": Tags may not have any characters that encodeURIComponent encodes.

**Comment by wwayne** [comment]
fixed in the new version `v0.1.9`

**Comment by eAmin** [comment]
This use it on Next.js

Module not found: Can't resolve 'react-horizontal-scrolling'
   8 | import Card3 from '../../subject/Card3/Card3';
   9 | import usePreventBodyScroll from '../component/hooks/usePreventBodyScroll';
> 10 | import HorizontalScroll from 'react-horizontal-scrolling';
