### ISSUE TITLE
Module not found: Can't resolve 'react-horizontal-scrolling'

### ISSUE THREAD

**Issue by webagent-dev** [dapi-labs/react-horizontal-scrolling#5]
<img width="1035" alt="Screenshot 2022-09-11 at 23 59 13" src="https://user-images.githubusercontent.com/78637825/189552639-67cd4a6f-e237-4919-9335-396470260227.png">
<img width="1680" alt="Screenshot 2022-09-12 at 00 01 20" src="https://user-images.githubusercontent.com/78637825/189552644-d875003d-21c6-4bd7-8020-45a3b1d37fde.png">

# Module not found: Can't resolve 'react-horizontal-scrolling' 

## i was trying to use react horizontal scrolling so i  got this error <span>Module not found: Can't resolve 'react-horizontal-scrolling'</span>

# when i check the package folder on my node_module i got this

<img width="1680" alt="Screenshot 2022-09-12 at 00 07 02" src="https://user-images.githubusercontent.com/78637825/189552911-c3e738f8-4258-4de8-bd12-fbd32e474b74.png">

**Comment by wwayne** [comment]
Fix in the new version `v0.1.12`

**Comment by webagent-dev** [comment]
> Fix in the new version `v0.1.12`

ok.. Thanks let me just it out
