### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by webagent-dev** [dapi-labs/react-horizontal-scrolling#6]
## please am working on a personal project and this liberty is the only thing that is given me issues please I will appreciate it if you can put me through getting this solve please
<img width="1680" alt="Screenshot 2022-09-13 at 13 26 44" src="https://user-images.githubusercontent.com/78637825/190868520-26a7221c-f7fb-41ad-ab3c-7209802983e0.png">

**Comment by wwayne** [comment]
Hi, can you try again and let me know if it works now, thanks

**Comment by wwayne** [comment]
published new version `0.1.13`
